Acme\ChessBundle\Entity\Game:
    type: entity
    table: game
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tableId:
            type: string
            length: '32'
        position:
            type: string
            length: '70'
        log:
            type: text
        castlings:
            type: string
            length: '32'
        tieProposal:
            type: string
            length: '16'
        status:
            type: string
            length: '16'
    lifecycleCallbacks: {  }
