chess_homepage:
    pattern:  /chess/
    defaults: { _controller: AcmeChessBundle:Default:index }

chess_createTable:
    pattern:  /chess/createtable/{color}
    defaults: { _controller: AcmeChessBundle:Default:createTable }

chess_table:
    pattern:  /chess/table/{tableId}/{player}
    defaults: { _controller: AcmeChessBundle:Default:table }

chess_moveTile:
    pattern:  /chess/moveTile/{tableId}/{fromX},{fromY}-{toX},{toY}
    defaults: { _controller: AcmeChessBundle:Default:moveTile }

chess_checkGameState:
    pattern:  /chess/checkGameState/{tableId}/{player}
    defaults: { _controller: AcmeChessBundle:Default:checkGameState }

chess_proposeTie:
    pattern:  /chess/proposeTie/{tableId}/{player}
    defaults: { _controller: AcmeChessBundle:Default:proposeTie }
