chess_homepage:
    pattern:  /chess/
    defaults: { _controller: AcmeChessBundle:Default:index }

chess_createTable:
    pattern:  /chess/createtable/{color}
    defaults: { _controller: AcmeChessBundle:Default:createTable }

chess_table:
    pattern:  /chess/table/{tableId}/{color}
    defaults: { _controller: AcmeChessBundle:Default:table }

chess_startGame:
    pattern:  /chess/startGame/{tableId}
    defaults: { _controller: AcmeChessBundle:Default:startGame }

chess_moveTile:
    pattern:  /chess/moveTile/{tableId}/{fromX},{fromY}-{toX},{toY}
    defaults: { _controller: AcmeChessBundle:Default:moveTile }

chess_checkGameState:
    pattern:  /chess/checkGameState/{tableId}/{color}
    defaults: { _controller: AcmeChessBundle:Default:checkGameState }
