chess_homepage:
    pattern:  /chess/
    defaults: { _controller: AcmeChessBundle:Default:index }

chess_createTable:
    pattern:  /chess/createtable/{player}
    defaults: { _controller: AcmeChessBundle:Default:createTable }

chess_table:
    pattern:  /chess/table/{tableId}/{player}
    defaults: { _controller: AcmeChessBundle:Default:table }

chess_moveTile:
    pattern:  /chess/moveTile/{tableId}
    defaults: { _controller: AcmeChessBundle:Default:moveTile }
    methods:  [POST]

chess_checkGameState:
    pattern:  /chess/checkGameState/{tableId}/{player}
    defaults: { _controller: AcmeChessBundle:Default:checkGameState }

chess_tieProposal:
    pattern:  /chess/tieProposal/{tableId}/{player}
    defaults: { _controller: AcmeChessBundle:Default:tieProposal }
    methods:  [POST]

chess_surrender:
    pattern:  /chess/surrender/{tableId}/{player}
    defaults: { _controller: AcmeChessBundle:Default:surrender }
    methods:  [POST]
