parameters:
    acme.controller.chess.class: Acme\ChessBundle\Controller\DefaultController

services:
    acme.chess.controller:
        class: %acme.controller.chess.class%

    kernel.listener.chess_exception_listener:
        class: Acme\ChessBundle\Listener\ExceptionListener
        arguments: [@templating, @kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
