parameters:
#    acme_chess.example.class: Acme\ChessBundle\Example

services:
#    acme_chess.example:
#        class: %acme_chess.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
